image:
  file: Dockerfile

tasks:
  - init: echo $gamslice > /home/usr/gams/gamslice.txt    

ports:
- port: 8080
  onOpen: open-preview
- port: 8087
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
