image:
  file: Dockerfile

tasks:
  - before: printf 'export PATH="/opt/gams:$PATH" >> $HOME/.bashrc && \
            mkdir -p ~/.local/share/GAMS && \
            echo -e $gamslice > ~/.local/share/GAMS/gamslice.txt && \
            exit

ports:
- port: 8080
  onOpen: open-preview
- port: 8087
  onOpen: open-preview
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - lolow.gams
