image:
  file: Dockerfile

tasks:
  - init: mkdir -p ~/.local/share/GAMS && echo -e $gamslice > ~/.local/share/GAMS/gamslice.txt

ports:
- port: 8080
  onOpen: open-preview
- port: 8087
  onOpen: open-preview
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - https://github.com/lolow/gams