image:
  file: Dockerfile

tasks:
  - name: Export gams licence
    command: mkdir -p ~/.local/share/GAMS && echo -e $gamslice > ~/.local/share/GAMS/gamslice.txt
  - name: Change PATH to include GAMS PATH
    command: export PATH="/opt/gams:$PATH"

ports:
- port: 8080
  onOpen: open-preview
- port: 8087
  onOpen: open-preview
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - lolow.gams
