image:
  file: Dockerfile

tasks:
  - init: echo $gamslice > /opt/gams/gamslice.txt
    command: echo $gamslice > /opt/gams/gamslice.txt

ports:
- port: 8080
  onOpen: open-preview
- port: 8087
  onOpen: open-preview
- port: 8888
  onOpen: open-browser
