image:
  file: Dockerfile

tasks:
  - before: |
    printf 'export PATH="/opt/gams:$PATH"' >> $HOME/.bashrc 
    mkdir -p $HOME/.local/share/GAMS
    echo -e $gamslice > $HOME/.local/share/GAMS/gamslice.txt

ports:
- port: 8080
  onOpen: open-preview
- port: 8087
  onOpen: open-preview
- port: 8888
  onOpen: open-browser

vscode:
  extensions:
    - lolow.gams
